export { Catalog } from './catalog';
export { Home } from './home';
export { Product } from './product';
export { Products } from './products';
export { About } from './about';
export { DeliveryInfo } from './delivery-info';
export { PersonalProfile } from './personal-profile';
export { BonusProgram } from './bonus-program';
export { Refund } from './refund';
